name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install rumps
        pip install .
    
    - name: Build macOS app
      run: |
        pyinstaller claude_usage_tracker_final.spec
    
    - name: Create DMG
      run: |
        ./create_dmg.sh
    
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: ClaudeUsageTracker-macOS
        path: dist/*.dmg
    
  create-release:
    needs: build-macos
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ClaudeUsageTracker-macOS
        path: dist/
    
    - name: Get version
      id: get_version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "VERSION=v${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        name: Claude Usage Tracker ${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Claude Usage Tracker ${{ steps.get_version.outputs.VERSION }}
          
          ### Installation
          
          Download the `.dmg` file below and drag Claude Usage Tracker to your Applications folder.
          
          ### Features
          - Track Claude API usage and costs
          - Menu bar widget for quick access
          - Floating window display
          - Command line interface
          
          ### Changelog
          - See [CHANGELOG.md](https://github.com/AndyBoWu/claude-usage-tracker/blob/main/CHANGELOG.md) for details
        files: |
          dist/*.dmg
        draft: false
        prerelease: false